name: conda_dataset
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - _py-xgboost-mutex=2.0=gpu_0
  - blas=1.1=openblas
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8deb56e_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cloudpickle=3.1.0=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.0=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.4.0=0
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudnn=8.9.7.29=hbc23b4c_3
  - cupy=13.3.0=py310h189a05f_2
  - cupy-core=13.3.0=py310h5da974a_2
  - fastrlock=0.8.2=py310hc6cd4ac_2
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py310h06a4308_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=7_ha36c22a_netlib
  - libcublas=12.4.2.65=0
  - libcufft=11.2.0.44=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.6.0.99=0
  - libcusparse=12.3.0.142=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=7_ha36c22a_netlib
  - libllvm14=14.0.6=hecde1de_4
  - libnpp=12.2.5.2=0
  - libnvfatbin=12.4.127=0
  - libnvjitlink=12.4.99=0
  - libnvjpeg=12.3.1.89=0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.21.12=hfc55251_2
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxgboost=2.1.2=cuda118_h09a87be_0
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=19.1.3=h024ca30_0
  - llvmlite=0.43.0=py310h6a678d5_0
  - lz4-c=1.9.4=h6a678d5_1
  - magma=2.6.2=hc72dce7_0
  - markupsafe=2.1.3=py310h5eee18b_0
  - mkl=2022.2.1=h6508926_16999
  - mkl-service=2.4.0=py310h9263142_0
  - mkl_fft=1.3.8=py310h88d2f6f_0
  - mkl_random=1.2.4=py310h378cecd_2
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - nccl=2.23.4.1=h03a54cd_2
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py310h06a4308_0
  - ninja=1.12.1=h297d8ca_0
  - numba=0.60.0=py310h5dc88bb_0
  - openblas=0.3.28=pthreads_h6ec200e_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.3=py310h5eaa309_1
  - patsy=0.5.6=pyhd8ed1ab_0
  - pillow=10.4.0=py310h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - py-xgboost=2.1.2=cuda118_pyh41db038_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.15=he870216_1
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=1.13.1=cuda112py310he33e0d6_200
  - pytorch-cuda=12.4=hc786d27_6
  - pytorch-mutex=1.0=cpu
  - pytorch-tabnet=4.1.0=pyhd8ed1ab_0
  - pyyaml=6.0.1=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_0
  - scikit-learn=1.5.2=py310h27f47ee_1
  - setuptools=75.1.0=py310h06a4308_0
  - shap=0.45.1=cuda118py310hd5e5b8b_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.7=h1b44611_0
  - slicer=0.0.8=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - statsmodels=0.14.4=py310hf462985_0
  - sympy=1.13.2=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=0.13.1=py310_cpu
  - torchtriton=3.0.0=py310
  - torchvision=0.14.1=cuda112py310h7928a00_0
  - typing_extensions=4.11.0=py310h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - urllib3=2.2.3=py310h06a4308_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - alabaster==0.7.16
      - albumentations==1.3.1
      - antlr4-python3-runtime==4.9.3
      - anyio==4.6.0
      - arabic-reshaper==3.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asn1crypto==1.5.1
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - boto3==1.36.9
      - botocore==1.36.9
      - build==1.2.2.post1
      - click==8.1.8
      - coloredlogs==15.0.1
      - comm==0.2.2
      - contourpy==1.3.0
      - coverage==5.3.1
      - cryptography==44.0.0
      - cssselect2==0.7.0
      - cycler==0.12.1
      - data-gradients==0.3.2
      - debugpy==1.8.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - docutils==0.17.1
      - einops==0.3.2
      - eva-decord==0.6.1
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - flatbuffers==25.1.24
      - fonttools==4.54.1
      - fqdn==1.5.1
      - fsspec==2024.9.0
      - future==1.0.0
      - grpcio==1.70.0
      - h11==0.14.0
      - html5lib==1.1
      - httpcore==1.0.6
      - httpx==0.27.2
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - imagededup==0.3.2
      - imageio==2.37.0
      - imagesize==1.4.1
      - iopath==0.1.10
      - ipykernel==6.29.5
      - ipython==8.28.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.1
      - jmespath==1.0.1
      - json-tricks==3.16.1
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.0.2
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - numpy==1.23.0
      - omegaconf==2.3.0
      - onnx==1.15.0
      - onnxruntime==1.15.0
      - onnxsim==0.4.36
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.11.0.86
      - oscrypto==1.3.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pip-tools==7.4.1
      - platformdirs==4.3.6
      - portalocker==2.10.1
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - protobuf==3.20.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pydeprecate==0.3.2
      - pygments==2.18.0
      - pyhanko==0.25.3
      - pyhanko-certvalidator==0.26.5
      - pyparsing==3.1.4
      - pypdf==5.2.0
      - pyproject-hooks==1.2.0
      - python-bidi==0.6.3
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytz==2024.2
      - pywavelets==1.8.0
      - pyzmq==26.2.0
      - qrcode==8.0
      - qudida==0.0.4
      - rapidfuzz==3.11.0
      - referencing==0.35.1
      - reportlab==3.6.13
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.20.0
      - s3transfer==0.11.2
      - scikit-image==0.24.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - soupsieve==2.6
      - sphinx==4.0.3
      - sphinx-rtd-theme==1.3.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stack-data==0.6.3
      - stringcase==1.2.0
      - super-gradients==3.7.1
      - svglib==1.5.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - termcolor==1.1.0
      - terminado==0.18.1
      - tifffile==2025.1.10
      - tinycss2==1.3.0
      - tomli==2.0.2
      - torchmetrics==0.8.0
      - tornado==6.4.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - treelib==1.6.1
      - types-python-dateutil==2.9.0.20241003
      - tzlocal==5.2
      - ultralytics==8.3.9
      - ultralytics-thop==2.0.9
      - uri-template==1.3.0
      - uritools==4.0.3
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - xhtml2pdf==0.2.11
prefix: /home/baptiste/miniconda3/envs/conda_both
